### ISSUE TITLE
Add option to double up exposure stepping

### ISSUE THREAD

**Issue by bcoyle** [untoxa/2bit-pxlr-studio-next#4]
Toggle option to have even more granular stepping of exposure. A step between every current step might be perfect. Harsher outdoor light is difficult to dial in.

![1 - outdoor](https://user-images.githubusercontent.com/8592223/180525962-85ac4f62-72a8-427c-9884-0b7c1634b9cc.JPEG)
![2 - outdoor shade](https://user-images.githubusercontent.com/8592223/180525972-ac938093-2fdf-4730-a844-d36c2121a49d.JPEG)
![3 - inside](https://user-images.githubusercontent.com/8592223/180525983-54b4ea6a-8ee7-4897-9c5d-1bc23e03eda9.JPEG)

**Comment by untoxa** [comment]
why did you close this? i was going to add additional exposure steps for the manual mode...

**Comment by bcoyle** [comment]
![Untitled-4](https://user-images.githubusercontent.com/8592223/184021436-1a021a39-33f9-4725-9e76-c34adbb24ec8.jpg)

looking good now
